//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Finder.h
//  @ Date : 2010-06-02
//  @ Author : 
//
//



#if !defined(_FINDER_H)
#define _FINDER_H

#include <qvector.h>
#include <qstring.h>
#include <qpoint.h>
#include "CKey.h"


extern char *keyType[7];
extern int gKeyNum;

class Finder {
public:
        static CKey* findKey( QVector< CKey > &keys,  QPoint pt);
};

#endif  //_FINDER_H
