//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Finder.cpp
//  @ Date : 2010-06-02
//  @ Author : 
//
//


#include "Finder.h"
#include <stdio.h>
#include <qrect.h>
CKey* Finder::findKey( QVector<CKey> &keys, QPoint pt) {
	
	QRect rect;
        CKey *pKey;
	int i;

	i = 0;
        while( i < 7)
	{
                pKey = keys[ i ];
		rect = pKey->getArea();
		
                if ( pKey->contains( pt ) == true )
		{
                        return pKey;
		}

		i++;
	}
        return NULL;
}

